name: Create & Publish Release

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: 📡 Checkout
        uses: actions/checkout@v3

      # Configures NodeJS.
      - name: ⚙️ Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      # Installs & builds.
      - name: 🔧 Install Dependencies
        run: npm install
      - name: 🧱 Build Project
        run: npm run build

      # Gets the game system name.
      - name: 📄 Get Game System Name
        id: game_system_name
        uses: notiz-dev/github-action-json-property@release
        with:
          path: dist/system.json
          prop_path: name

      # Gets the version tag.
      - name: 🏷️ Get Version Tag
        id: version
        uses: ncipollo/semantic-version-action@v1

      # Generates the changelog.
      - name: 📜 Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Creates the ZIP artifact.
      - name: 📦 Create ZIP Archive
        run: |
          cd dist/
          zip -r ../{{ steps.game_system_name.outputs.prop }}-fvtt_${{ steps.version.outputs.tag }}.zip *
      
      # Creates the release with its artifacts and description.
      - name: 🚀 Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./dist/system.json, {{ steps.game_system_name.outputs.prop }}-fvtt_${{ steps.version.outputs.tag }}.zip"
          body: ${{ steps.changelog.outputs.changelog }}

      # Publishes the release to the FoundryVTT's package repository.
      - name: 🚩 Publish Module to FoundryVTT Website
        uses: Varriount/fvtt-autopublish@v1.0.6
        with:
          username: ${{ secrets.FOUNDRY_ADMIN_USERNAME }}
          password: ${{ secrets.FOUNDRY_ADMIN_PASSWORD }}
          module-id: ${{ secrets.FOUNDRY_ADMIN_MODULE_ID }}
          manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.tag }}/system.json
          manifest-file: dist/system.json